Morseovka - Pilcik
turecekt/vs_project pull request #163
Opened 2021-12-17 13:10 UTC by Pilous15

2021-12-29 20:07 UTC, turecekt requested changes

2021-12-29 20:07 UTC, turecekt commented on Morseovka/Morseovka.py
> +    dekodovani(text_k_dekodovani)
```suggestion
if __name__ == '__main__':
    print("\n\n\n\t\tMorse Code Generator")
    ch = input("Stiskni E k zakodovani nebo D k Dekodovani : ")
    if ch == 'E' or ch == 'e': #stiskni "e" a muzes zakodovat svoji vetu,slovo nebo pismeno
        text_k_zakodovani = input("Vlož text k zakodovani : ").upper()
        zakodovani(text_k_zakodovani)
    else:
        text_k_dekodovani = input("Vlož text k dekodovani : ") #stiskni jakoukoli jinou klavesu a muzes dekodovat svoji vetu,slovo nebo pismeno
        dekodovani(text_k_dekodovani)
```

2022-01-26 09:59 UTC, turecekt requested changes
Je potřeba přesunout zdrojové kódy z adresáře Morseovka do kořenového adresáře kvůli nalezení pytestem.
Soubor Morseovka.pyproj přejmenovat na .Morseovka.pyproj
Ty testy, když jsou napsány jako členské metody třídy, musí mít v definici parametr self
Následně opravit chyby statické analýzy vygenerované nástrojem flake8

V sekci Actions ve vašem repozitáři uvidíte výsledky testu po každém odjetí commitů do repozitáře.

2022-01-29 11:52 UTC, turecekt requested changes

2022-01-29 11:52 UTC, turecekt commented on Morseovka.py
> +    assert zakodovani('".-"') == 'A'
```suggestion
    assert zakodovani('.-') == 'A'
```

2022-01-29 11:52 UTC, turecekt commented on Morseovka.py
> +    assert dekodovani('"A"') == '.-'
```suggestion
    assert dekodovani('A') == '.-'
```

2022-01-29 11:52 UTC, turecekt commented on Morseovka.py
> +            zakodovany_text = zakodovany_text + MORSE_CODE_DICT.get(pismena) + " " #vyhleda slovnik a prida odpovidajici znak + mezeru
tady to generuje problém s mezerou přidávanou navíc na konci překladu (za posledním zakódovaným písmenem)

2022-02-02 23:55 UTC, turecekt requested changes

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +    assert zakodovani('.-') == 'A'
```suggestion
    assert zakodovani('A') == '.-'
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +    assert dekodovani('A') == '.-'
```suggestion
    assert dekodovani('.-') == 'A'
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +    print(zakodovany_text) #vypis zakodovany text
```suggestion
    return zakodovany_text
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +    print(normal) #vypis dekodovanz text
```suggestion
    return normal
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +        zakodovani(text_k_zakodovani)
```suggestion
        print(zakodovani(text_k_zakodovani))
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +        dekodovani(text_k_dekodovani)
```suggestion
        print(dekodovani(text_k_dekodovani))
```

2022-02-02 23:55 UTC, turecekt commented on Morseovka.py
> +
```suggestion
```

2022-08-24 14:17 UTC, pilcikpatrik commented
Odevzdání úkolů s opravou testů (Morseovka) - Pilčík

2022-08-24 14:53 UTC, closed without merging