hubik_santler_vs_projekt
turecekt/vs_project pull request #228
Opened 2023-01-21 22:59 UTC by martinhubik

2023-01-23 10:33 UTC, turecekt requested changes
- povolit workflow Python checker v sekci Actions

2023-01-24 17:29 UTC, martinhubik commented
Mělo by být opraveno

2023-01-24 18:07 UTC, turecekt requested changes
- upravit docstringy k parametrům kde je chyba jako návrh v code review
- upravit website url na hlavní stránce repa na korektní

2023-01-24 18:07 UTC, turecekt commented on main.py
> +    :returns: input numbers
```suggestion
    :param filename: name of the input file
    :type filename: string
    :raises: :class:`FileNotFoundError`: no file under filename is found
    :return: input numbers
```

2023-01-24 18:27 UTC, martinhubik commented
Upraveno

2023-01-24 19:12 UTC, turecekt approved these changes

2023-01-29 22:56 UTC, turecekt requested changes
poslední detail pro přehlednější zobrazení v dokumentaci

2023-01-29 22:56 UTC, turecekt commented on miniMax/main.py
> +import string
```suggestion
```

2023-01-29 22:56 UTC, turecekt commented on miniMax/main.py
> +def input_file(filename: string) -> list[int]:
```suggestion
def input_file(filename: str) -> list[int]:
```

2023-01-29 23:53 UTC, martinhubik commented
opraveno

2023-01-30 00:44 UTC, turecekt approved these changes

2024-06-05 08:47 UTC, closed without merging